from django.urls import path
from .views import (
    register_view,
    login_view,
    home,
    search_view,
    send_invite,
    chat_details_view,
    send_message,
    friend_request_list_view,
    accept_friend_request,
    map_view,
    update_location,
    profile_view,
    logout_view,
    camera_view,
    send_snap_view,
)

urlpatterns = [
    path("register/", register_view, name="register-user"),
    path("login/", login_view, name="login"),
    path("", home, name="home"),
    path("search/", search_view, name="search-users"),
    path("send-invite/<int:id>", send_invite, name="send-invite"),
    path("chat-details/<int:id>", chat_details_view, name="chat-details"),
    path("send-message/<int:id>", send_message, name="send-message"),
    path("friend-requests/", friend_request_list_view, name="friend-requests"),
    path("accept-friend-request/<int:id>", accept_friend_request, name="accept-friend"),
    path("map/", map_view, name="map"),
    path("update-location/", update_location, name="update-location"),
    path("profile/", profile_view, name="profile"),
    path("logout/", logout_view, name="logout"),
    path("camera/", camera_view, name="camera"),
    path("send-snap/", send_snap_view, name="send-snap"),
]
